# 文件名: report_generator.py
# 存放位置: app/ 文件夹下

import os

def generate_markdown_report(analysis_dict):
    """单篇论文的 Markdown 生成"""
    title = analysis_dict.get('title', '未提取到标题')
    md = f"### 📄 {title}\n\n"
    md += f"**🎯 研究问题:** {analysis_dict.get('research_problem', '未明确提及')}\n\n"
    md += f"**🛠️ 核心方法:** {analysis_dict.get('method', '未明确提及')}\n\n"
    md += f"**📊 数据集:** {analysis_dict.get('dataset', '未明确提及')}\n\n"
    md += f"**💡 创新点:** {analysis_dict.get('innovation', '未明确提及')}\n\n"
    md += f"**⚠️ 局限性:** {analysis_dict.get('limitations', '未明确提及')}\n\n"
    return md

def generate_combined_report(analyses_list, literature_review):
    """
    【新增】组合多篇论文结果与综述，生成最终的完整 Markdown
    """
    md = "# 📚 OpenResearch 综合文献分析报告\n\n"
    
    if literature_review:
        md += "## 🌟 AI 总结：文献综述 (Related Work)\n"
        md += f"{literature_review}\n\n---\n\n"
        
    md += "## 📑 单篇论文详细解析\n\n"
    for idx, analysis in enumerate(analyses_list):
        md += f"## 文献 [{idx+1}]\n"
        md += generate_markdown_report(analysis)
        md += "---\n"
        
    md += "*Generated by OpenResearch Copilot*"
    return md

def save_report(md_content, filename="report.md"):
    os.makedirs("outputs", exist_ok=True)
    filepath = os.path.join("outputs", filename)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(md_content)
    return filepath